// Emberfall core content. Tuned for a gentle start and increasingly demanding late game.
export const ARENA_W=1600; export const ARENA_H=900;
export type WeaponId="pistol"|"smg"|"shotgun"|"lance"|"mortar"|"railgun"|"arcjet"|"swarmer";
export interface Weapon{id:WeaponId;name:string;desc:string;cost:number;dmg:number;cooldown:number;speed:number;count:number;spread:number;pierce:number;radius:number;life:number;explode?:number;homing?:number;knockback:number;color:string;}
export const WEAPONS:Record<WeaponId,Weapon>={
 pistol:{id:"pistol",name:"Sidearm",desc:"Reliable. Nothing fancy.",cost:0,dmg:12,cooldown:.28,speed:720,count:1,spread:.03,pierce:0,radius:4,life:1.1,knockback:90,color:"#ffd48a"},
 smg:{id:"smg",name:"Cinder SMG",desc:"Fast spray, low damage per shot.",cost:220,dmg:7,cooldown:.09,speed:820,count:1,spread:.16,pierce:0,radius:3,life:.8,knockback:40,color:"#ffb15c"},
 shotgun:{id:"shotgun",name:"Scattergun",desc:"Six pellets. Brutal up close.",cost:300,dmg:9,cooldown:.62,speed:700,count:6,spread:.5,pierce:0,radius:3.5,life:.45,knockback:190,color:"#ff8f5e"},
 lance:{id:"lance",name:"Ion Lance",desc:"Pierces enemies in a line.",cost:420,dmg:18,cooldown:.5,speed:1150,count:1,spread:0,pierce:6,radius:5,life:1.1,knockback:60,color:"#7fe8ff"},
 mortar:{id:"mortar",name:"Ember Mortar",desc:"Explosive shots with big area damage.",cost:520,dmg:26,cooldown:.85,speed:480,count:1,spread:.05,pierce:0,radius:7,life:1.6,explode:110,knockback:140,color:"#ff6b4a"},
 railgun:{id:"railgun",name:"Railgun",desc:"One huge piercing slug.",cost:700,dmg:70,cooldown:1.05,speed:1600,count:1,spread:0,pierce:10,radius:6,life:1.2,knockback:260,color:"#c7b3ff"},
 arcjet:{id:"arcjet",name:"Arcjet",desc:"Triple stream of sparks.",cost:640,dmg:11,cooldown:.2,speed:900,count:3,spread:.28,pierce:1,radius:3.5,life:.9,knockback:55,color:"#8affc8"},
 swarmer:{id:"swarmer",name:"Swarmer Pods",desc:"Four homing darts.",cost:820,dmg:14,cooldown:.6,speed:520,count:4,spread:1.2,pierce:0,radius:4,life:2.2,homing:4.2,knockback:50,color:"#ff9ede"}
};
export const WEAPON_ORDER:WeaponId[]=["pistol","smg","shotgun","lance","arcjet","mortar","railgun","swarmer"];
export type PerkId="dmg"|"rate"|"speed"|"hp"|"pierce"|"multishot"|"crit"|"lifesteal"|"blast"|"thorns"|"magnet"|"dash"|"regen"|"velocity"|"greed"|"shield"|"orbit"|"chain";
export interface Perk{id:PerkId;name:string;desc:string;max:number;rare?:boolean;}
export const PERKS:Perk[]=[
{id:"dmg",name:"Hot Rounds",desc:"+18% damage",max:12},{id:"rate",name:"Trigger Discipline",desc:"+14% fire rate",max:10},{id:"speed",name:"Light Boots",desc:"+9% move speed",max:8},{id:"hp",name:"Plating",desc:"+22 max health",max:10},{id:"pierce",name:"Punch-Through",desc:"Shots pierce +1 enemy",max:5},{id:"multishot",name:"Split Barrel",desc:"+1 projectile per shot",max:4,rare:true},{id:"crit",name:"Weak Points",desc:"+8% crit chance",max:8},{id:"lifesteal",name:"Siphon",desc:"2% damage heals you",max:6},{id:"blast",name:"Volatile Rounds",desc:"Kills explode",max:5,rare:true},{id:"thorns",name:"Spiked Hull",desc:"Attackers take damage",max:6},{id:"magnet",name:"Scavenger",desc:"Bigger pickup radius",max:5},{id:"dash",name:"Kinetic Coils",desc:"Lower dash cooldown",max:5},{id:"regen",name:"Nanoweave",desc:"Regenerate health",max:6},{id:"velocity",name:"Overpressure",desc:"Faster projectiles",max:5},{id:"greed",name:"Prospector",desc:"More gold and XP",max:6},{id:"shield",name:"Bulwark",desc:"Rechargeable shield",max:5,rare:true},{id:"orbit",name:"Ember Orbs",desc:"Damage nearby enemies",max:4,rare:true},{id:"chain",name:"Arc Static",desc:"Hits chain to nearby foes",max:4,rare:true}
];
export const PERK_MAP:Record<string,Perk>=Object.fromEntries(PERKS.map(p=>[p.id,p]));
export type EnemyKind="grunt"|"swarm"|"shooter"|"charger"|"tank"|"splitter"|"shard"|"healer"|"bomber"|"sniper"|"warden";
export interface EnemyDef{kind:EnemyKind;name:string;hp:number;speed:number;dmg:number;r:number;xp:number;gold:number;color:string;cost:number;shootCd?:number;bulletSpeed?:number;bulletDmg?:number;}
export const ENEMIES:Record<EnemyKind,EnemyDef>={
 grunt:{kind:"grunt",name:"Husk",hp:34,speed:92,dmg:10,r:15,xp:5,gold:4,color:"#ff7a5c",cost:1},swarm:{kind:"swarm",name:"Mite",hp:14,speed:150,dmg:6,r:10,xp:3,gold:2,color:"#ffd166",cost:.6},shooter:{kind:"shooter",name:"Spitter",hp:40,speed:70,dmg:8,r:15,xp:8,gold:7,color:"#a6e3a1",cost:2,shootCd:1.8,bulletSpeed:300,bulletDmg:9},charger:{kind:"charger",name:"Lunger",hp:52,speed:110,dmg:16,r:17,xp:10,gold:8,color:"#ff5fa2",cost:2.4},tank:{kind:"tank",name:"Bulwark",hp:190,speed:55,dmg:20,r:26,xp:22,gold:20,color:"#9aa7ff",cost:5},splitter:{kind:"splitter",name:"Cyst",hp:70,speed:78,dmg:12,r:20,xp:12,gold:10,color:"#c084fc",cost:3},shard:{kind:"shard",name:"Shard",hp:18,speed:165,dmg:7,r:9,xp:2,gold:1,color:"#e0a3ff",cost:0},healer:{kind:"healer",name:"Mender",hp:66,speed:82,dmg:6,r:16,xp:16,gold:14,color:"#7fe8ff",cost:3.5},bomber:{kind:"bomber",name:"Bloat",hp:58,speed:96,dmg:34,r:21,xp:14,gold:12,color:"#ffa94d",cost:3},sniper:{kind:"sniper",name:"Lancer",hp:46,speed:60,dmg:8,r:15,xp:18,gold:15,color:"#fefefe",cost:4,shootCd:2.6,bulletSpeed:620,bulletDmg:18},warden:{kind:"warden",name:"Warden",hp:130,speed:88,dmg:18,r:22,xp:26,gold:24,color:"#ff4d6d",cost:6,shootCd:1.4,bulletSpeed:380,bulletDmg:12}
};
export interface BossDef{wave:number;name:string;title:string;hp:number;speed:number;r:number;color:string;gold:number;xp:number;pattern:"ring"|"spiral"|"shotgun"|"summon"|"beamer"|"final";}
export const BOSSES:BossDef[]=[{wave:5,name:"Cinderjaw",title:"the First Ember",hp:900,speed:74,r:42,color:"#ff7a3d",gold:160,xp:120,pattern:"ring"},{wave:10,name:"Vex Coil",title:"Spiral of Teeth",hp:1700,speed:86,r:44,color:"#c084fc",gold:240,xp:200,pattern:"spiral"},{wave:15,name:"Bulwark Prime",title:"the Unmoved",hp:3000,speed:62,r:54,color:"#9aa7ff",gold:340,xp:300,pattern:"shotgun"},{wave:20,name:"The Broodmother",title:"Mother of Mites",hp:4200,speed:80,r:50,color:"#a6e3a1",gold:460,xp:420,pattern:"summon"},{wave:25,name:"Nulleye",title:"Watcher in the Ash",hp:6000,speed:96,r:46,color:"#7fe8ff",gold:600,xp:560,pattern:"beamer"},{wave:30,name:"Emberfall",title:"the Last Sky",hp:9500,speed:92,r:60,color:"#ff4d6d",gold:1000,xp:900,pattern:"final"}];
export const FINAL_WAVE=30;
export const UNLOCKS:{wave:number;kind:EnemyKind}[]=[{wave:1,kind:"grunt"},{wave:2,kind:"swarm"},{wave:3,kind:"shooter"},{wave:4,kind:"charger"},{wave:6,kind:"bomber"},{wave:7,kind:"splitter"},{wave:9,kind:"tank"},{wave:11,kind:"healer"},{wave:13,kind:"sniper"},{wave:17,kind:"warden"}];
export interface MetaUpgrade{id:string;name:string;desc:string;max:number;cost:(lvl:number)=>number;}
export const META_UPGRADES:MetaUpgrade[]=[{id:"mHp",name:"Reinforced Frame",desc:"+15 starting max health",max:8,cost:l=>3+l*3},{id:"mDmg",name:"Ember Core",desc:"+6% damage",max:8,cost:l=>4+l*3},{id:"mGold",name:"Salvage Rights",desc:"+12% gold",max:6,cost:l=>3+l*2},{id:"mSpeed",name:"Servo Legs",desc:"+4% move speed",max:6,cost:l=>3+l*2},{id:"mStart",name:"Advance Pay",desc:"+60 starting gold",max:6,cost:l=>2+l*2},{id:"mRevive",name:"Failsafe",desc:"Start with an extra revive",max:3,cost:l=>8+l*8},{id:"mPerk",name:"Deep Training",desc:"Start with a free perk choice",max:3,cost:l=>6+l*6},{id:"mLuck",name:"Fortune",desc:"Improve rare perk odds",max:5,cost:l=>4+l*3}];
export interface AchievementDef{id:string;name:string;desc:string;}
export const ACHIEVEMENTS:AchievementDef[]=[{id:"first_blood",name:"First Blood",desc:"Kill your first enemy."},{id:"wave5",name:"Ember Slayer",desc:"Defeat Cinderjaw."},{id:"wave10",name:"Coil Breaker",desc:"Defeat Vex Coil."},{id:"wave15",name:"Immovable No More",desc:"Defeat Bulwark Prime."},{id:"wave20",name:"Brood Ender",desc:"Defeat The Broodmother."},{id:"wave25",name:"Eye Closer",desc:"Defeat Nulleye."},{id:"win",name:"Emberfall",desc:"Finish the campaign."},{id:"kills500",name:"Cull",desc:"Kill 500 enemies."},{id:"kills5000",name:"Exterminator",desc:"Kill 5,000 enemies."},{id:"coop",name:"Better Together",desc:"Clear a co-op wave."},{id:"flawless",name:"Untouched",desc:"Clear a wave without taking damage."},{id:"rich",name:"Tycoon",desc:"Hold 1,500 gold."},{id:"maxperk",name:"Specialist",desc:"Max out a perk."},{id:"endless20",name:"No End",desc:"Reach endless wave 20."},{id:"allweapons",name:"Armory",desc:"Own every weapon."}];
