import React,{useEffect,useRef,useState} from 'react'
import {createPlayer,spawnEnemy,spawnBoss,distance,gainXp,applyUpgrade,pickUpgrades,type Enemy,type Gem,type Player} from './SurvivorArena'

export default function SurvivorGame(){
 const canvas=useRef<HTMLCanvasElement>(null); const [paused,setPaused]=useState(false); const [levelUp,setLevelUp]=useState(false); const [options,setOptions]=useState<any[]>([]); const [stats,setStats]=useState({level:1,kills:0,time:0,hp:100}); const keys=useRef<Record<string,boolean>>({}); const player=useRef<Player>(createPlayer()); const enemies=useRef<Enemy[]>([]); const gems=useRef<Gem[]>([]); const bullets=useRef<any[]>([]); const last=useRef(performance.now()); const spawn=useRef(0); const eid=useRef(0); const bossMinute=useRef(-1)
 useEffect(()=>{const kd=(e:KeyboardEvent)=>{keys.current[e.key.toLowerCase()]=true;if(e.key==='Escape')setPaused(v=>!v)},ku=(e:KeyboardEvent)=>keys.current[e.key.toLowerCase()]=false;addEventListener('keydown',kd);addEventListener('keyup',ku);return()=>{removeEventListener('keydown',kd);removeEventListener('keyup',ku)}},[])
 useEffect(()=>{const c=canvas.current!,ctx=c.getContext('2d')!;let raf=0;const loop=(now:number)=>{const dt=Math.min(.033,(now-last.current)/1000);last.current=now;if(!paused&&!levelUp)update(dt);draw(ctx,c.width,c.height);raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf)},[paused,levelUp])
 function update(dt:number){const p=player.current;let dx=(keys.current.d?1:0)-(keys.current.a?1:0),dy=(keys.current.s?1:0)-(keys.current.w?1:0),m=Math.hypot(dx,dy)||1;p.x+=dx/m*p.speed*dt;p.y+=dy/m*p.speed*dt;const minute=stats.time/60;spawn.current-=dt;if(spawn.current<=0){spawn.current=Math.max(.12,.7-minute*.02);const count=minute>8?3:minute>4?2:1;for(let i=0;i<count;i++)enemies.current.push(spawnEnemy(++eid.current,minute))}const whole=Math.floor(stats.time/60);if(whole>0&&whole%2===0&&whole!==bossMinute.current){bossMinute.current=whole;enemies.current.push(spawnBoss(++eid.current,minute))}
 p.weapons.forEach(w=>{(w as any)._t=((w as any)._t??0)-dt;if((w as any)._t<=0){(w as any)._t=w.cooldown;const target=enemies.current.reduce((b,e)=>!b||distance(p,e)<distance(p,b)?e:b,null as Enemy|null);if(target){if(w.id==='nova'||w.id==='frost'){enemies.current.forEach(e=>{if(distance(target,e)<(w.id==='nova'?140:110))e.hp-=w.damage*p.power})}else bullets.current.push({x:p.x,y:p.y,target,damage:w.damage*p.power,speed:w.speed||360,color:w.color,life:2})}}});bullets.current.forEach(b=>{if(!b.target||b.target.hp<=0){b.life=0;return}const d=distance(b,b.target);if(d<18){b.target.hp-=b.damage;b.life=0}else{b.x+=(b.target.x-b.x)/d*b.speed*dt;b.y+=(b.target.y-b.y)/d*b.speed*dt}b.life-=dt});bullets.current=bullets.current.filter(b=>b.life>0)
 enemies.current.forEach(e=>{if(e.hp<=0)return;const d=distance(e,p);if(d<e.radius+18)p.hp-=Math.max(.3,12*dt-p.armor*.02);else{e.x+=(p.x-e.x)/d*e.speed*dt;e.y+=(p.y-e.y)/d*e.speed*dt}});let kills=0;enemies.current.forEach(e=>{if(e.hp<=0){kills++;gems.current.push({id:e.id,x:e.x,y:e.y,value:e.kind==='boss'?50:e.kind==='elite'?12:1});p.coins+=e.kind==='boss'?50:1}});enemies.current=enemies.current.filter(e=>e.hp>0)
 gems.current.forEach(g=>{const d=distance(g,p);if(d<p.magnet){const n=Math.max(1,d);g.x+=(p.x-g.x)/n*230*dt;g.y+=(p.y-g.y)/n*230*dt}if(distance(g,p)<20){const levels=gainXp(p,g.value);g.value=0;if(levels.length){setOptions(pickUpgrades(p));setLevelUp(true)}}});gems.current=gems.current.filter(g=>g.value>0);setStats(s=>({level:p.level,kills:s.kills+kills,time:s.time+dt,hp:Math.max(0,p.hp)}))}
 function draw(ctx:CanvasRenderingContext2D,w:number,h:number){const p=player.current;ctx.clearRect(0,0,w,h);ctx.fillStyle='#07101d';ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(w/2-p.x,h/2-p.y);ctx.strokeStyle='#12243b';for(let x=-3000;x<3000;x+=80){ctx.beginPath();ctx.moveTo(x,-3000);ctx.lineTo(x,3000);ctx.stroke()}for(let y=-3000;y<3000;y+=80){ctx.beginPath();ctx.moveTo(-3000,y);ctx.lineTo(3000,y);ctx.stroke()}gems.current.forEach(g=>{ctx.fillStyle='#fde047';ctx.beginPath();ctx.arc(g.x,g.y,6,0,7);ctx.fill()});enemies.current.forEach(e=>{ctx.fillStyle=e.color;ctx.beginPath();ctx.arc(e.x,e.y,e.radius,0,7);ctx.fill()});bullets.current.forEach(b=>{ctx.fillStyle=b.color;ctx.beginPath();ctx.arc(b.x,b.y,7,0,7);ctx.fill()});ctx.fillStyle='#60a5fa';ctx.beginPath();ctx.arc(p.x,p.y,18,0,7);ctx.fill();ctx.restore()}
 return <div className="survivor"><canvas ref={canvas} width={window.innerWidth} height={window.innerHeight}/><div className="survivorHud"><b>LEVEL {stats.level}</b><span>☠ {stats.kills}</span><span>⏱ {Math.floor(stats.time/60)}:{String(Math.floor(stats.time)%60).padStart(2,'0')}</span><div className="hp"><i style={{width:`${stats.hp}%`}}/></div><small>WASD • Collect XP • Survive</small></div>{paused&&<div className="survivorOverlay"><h1>PAUSED</h1><button onClick={()=>setPaused(false)}>RESUME</button></div>}{levelUp&&<div className="survivorOverlay"><h1>LEVEL UP</h1><div className="upgradeCards">{options.map(o=><button key={o.id} onClick={()=>{applyUpgrade(player.current,o.id);setLevelUp(false)}}><strong>{o.name}</strong><small>{o.level?'Upgrade weapon':'New weapon'}</small></button>)}</div></div>}</div>
}
