import { useEffect, useRef, useState } from "react";

type Ability = "nova" | "blink" | "shield" | "overdrive";
type Player = { x:number;y:number;hp:number;maxHp:number;speed:number;fire:number;dashCd:number;abilityCd:number;ability:Ability;abilityActive:number;color:string;dead:boolean;level:number;xp:number;nextXp:number;damage:number;shots:number;crit:number;armor:number;regen:number;lifesteal:number;score:number };
type Enemy = { x:number;y:number;r:number;hp:number;maxHp:number;speed:number;damage:number;kind:"husk"|"shooter"|"charger"|"boss";elite:boolean;phase:number };
type Bullet = { x:number;y:number;vx:number;vy:number;damage:number;life:number;enemy:boolean;r:number;owner:number };
type Mode = "menu"|"play"|"upgrade"|"pause"|"end";
const W=1200,H=675,MAX_WAVE=40;
const COLORS=["#ff9f43","#65e6ff"];
const UPGRADES = [
 ["🔥 OVERCHARGE","Damage +18%","damage"],["💨 LIGHT FEET","Speed +10%","speed"],["⚡ QUICK HANDS","Fire cooldown -14%","fire"],["❤️ TITAN CORE","Max HP +30 + heal","hp"],
 ["🛡 ARMOR PLATE","Damage taken -10%","armor"],["🎯 CRITICAL","Crit chance +8%","crit"],["🩸 VAMPIRIC","Heal 3% of damage","lifesteal"],["💚 REGEN","+1.5 HP/sec","regen"],
 ["🔫 TWIN BARREL","+1 projectile","shots"],["☄ HEAVY ROUNDS","Projectile damage +25%","damage"],["🏃 AFTERBURN","Dash cooldown -18%","dash"],["✨ ABILITY CORE","Ability cooldown -20%","ability"]
] as const;
const ABILITIES:Record<Ability,{name:string;desc:string}>={nova:{name:"NOVA",desc:"Blast nearby enemies for huge damage"},blink:{name:"BLINK",desc:"Teleport forward and become invulnerable"},shield:{name:"EMBER SHIELD",desc:"Absorb damage for 3 seconds"},overdrive:{name:"OVERDRIVE",desc:"Fire 2x faster and move faster for 5 seconds"}};
function meta():Record<string,number>{try{return JSON.parse(localStorage.getItem("emberfall.meta.v4")||"{}")}catch{return {}}}
function saveMeta(m:Record<string,number>){try{localStorage.setItem("emberfall.meta.v4",JSON.stringify(m))}catch{}}
export default function Game(){
 const canvasRef=useRef<HTMLCanvasElement>(null),keys=useRef<Record<string,boolean>>({}),last=useRef(0),raf=useRef(0);const[,force]=useState(0);const[screen,setScreen]=useState<Mode>("menu");
 const s=useRef({players:[] as Player[],enemies:[] as Enemy[],bullets:[] as Bullet[],wave:0,time:0,spawn:0,kills:0,credits:0,shake:0,message:"",meta:meta(),victory:false}).current;
 const redraw=()=>force(v=>v+1);
 useEffect(()=>{const d=(e:KeyboardEvent)=>{keys.current[e.code]=true;if(["Space","ArrowUp","ArrowDown","ArrowLeft","ArrowRight"].includes(e.code))e.preventDefault();if(e.code==="Escape")setScreen(x=>x==="play"?"pause":x==="pause"?"play":x)};const u=(e:KeyboardEvent)=>keys.current[e.code]=false;addEventListener("keydown",d);addEventListener("keyup",u);return()=>{removeEventListener("keydown",d);removeEventListener("keyup",u)}},[]);
 const begin=(count:1|2)=>{const make=(i:number):Player=>({x:W/2+(i?75:-75),y:H-100,hp:100,maxHp:100,speed:215,fire:0,dashCd:0,abilityCd:0,ability:i?"shield":"nova",abilityActive:0,color:COLORS[i],dead:false,level:1,xp:0,nextXp:30,damage:1,shots:1,crit:.05,armor:0,regen:0,lifesteal:0,score:0});s.players=Array.from({length:count},(_,i)=>make(i));s.enemies=[];s.bullets=[];s.wave=0;s.time=0;s.spawn=0;s.kills=0;s.credits=0;s.shake=0;s.victory=false;nextWave()};
 const nextWave=()=>{s.wave++;s.time=0;s.spawn=0;s.enemies=[];s.bullets=[];if(s.wave>MAX_WAVE){s.victory=true;setScreen("end");return}s.message=s.wave%5===0?"⚠ BOSS WAVE":"WAVE "+s.wave;setScreen("play");redraw()};
 const apply=(kind:string)=>{for(const p of s.players){if(kind==="damage")p.damage*=1.18;if(kind==="speed")p.speed*=1.10;if(kind==="fire")p.fire=Math.max(0,p.fire-.14);if(kind==="hp"){p.maxHp+=30;p.hp=p.maxHp}if(kind==="armor")p.armor=Math.min(.65,p.armor+.10);if(kind==="crit")p.crit=Math.min(.75,p.crit+.08);if(kind==="lifesteal")p.lifesteal=Math.min(.20,p.lifesteal+.03);if(kind==="regen")p.regen+=1.5;if(kind==="shots")p.shots=Math.min(5,p.shots+1);if(kind==="dash")p.dashCd=Math.max(.25,p.dashCd-.18);if(kind==="ability")p.abilityCd=Math.max(1,p.abilityCd-.20)}}nextWave()};
 const useAbility=(p:Player)=>{if(p.abilityCd>0||p.dead)return;const a=p.ability;if(a==="nova"){for(let i=s.enemies.length-1;i>=0;i--){const e=s.enemies[i];if(Math.hypot(e.x-p.x,e.y-p.y)<230){e.hp-=180*p.damage;if(e.hp<=0){s.enemies.splice(i,1);s.kills++;s.credits+=8}}}s.shake=12;p.abilityCd=12}else if(a==="blink"){const k=keys.current,dx=Number(!!k.KeyD)-Number(!!k.KeyA),dy=Number(!!k.KeyS)-Number(!!k.KeyW),l=Math.hypot(dx,dy)||1;p.x=Math.max(25,Math.min(W-25,p.x+dx/l*230));p.y=Math.max(25,Math.min(H-25,p.y+dy/l*230));p.abilityActive=.55;p.abilityCd=9}else if(a==="shield"){p.abilityActive=3;p.abilityCd=14}else{p.abilityActive=5;p.abilityCd=18}};
 const spawn=()=>{const w=s.wave,a=Math.random()*Math.PI*2,r=520,boss=w%5===0&&!s.enemies.some(e=>e.kind==="boss"),roll=Math.random();const kind:Enemy["kind"]=boss?"boss":w>=10&&roll<.10?"charger":roll<.24?"shooter":roll<.40?"charger":"husk";const scale=1+(w-1)*.085;const hp=(kind==="boss"?900+w*230:kind==="charger"?55+w*9:kind==="shooter"?42+w*7:28+w*6)*scale;s.enemies.push({x:W/2+Math.cos(a)*r,y:H/2+Math.sin(a)*r,r:kind==="boss"?46:kind==="charger"?20:kind==="shooter"?16:14,hp,maxHp:hp,speed:kind==="boss"?38+w:kind==="charger"?120+w*2:kind==="shooter"?58+w:76+w*1.6,damage:kind==="boss"?24+w:7+w*.85,kind,elite:kind!=="boss"&&w>=6&&Math.random()<Math.min(.28,w*.012),phase:0})};
 const update=(dt:number)=>{s.time+=dt;s.spawn-=dt;s.shake=Math.max(0,s.shake-dt*25);const w=s.wave;const cap=Math.min(90,7+Math.floor(w*2.2));if(s.spawn<=0&&s.enemies.length<cap){spawn();s.spawn=Math.max(.10,.78-w*.014)}
 s.players.forEach((p,i)=>{if(p.dead)return;const k=keys.current,left=!!k[i?"ArrowLeft":"KeyA"],right=!!k[i?"ArrowRight":"KeyD"],up=!!k[i?"ArrowUp":"KeyW"],down=!!k[i?"ArrowDown":"KeyS"];let dx=Number(right)-Number(left),dy=Number(down)-Number(up),l=Math.hypot(dx,dy)||1;dx/=l;dy/=l;if(!!k[i?"ShiftRight":"Space"]&&p.dashCd<=0){p.dashCd=.9;const boost=3.6;p.x=Math.max(25,Math.min(W-25,p.x+dx*p.speed*boost*.18));p.y=Math.max(25,Math.min(H-25,p.y+dy*p.speed*boost*.18))}p.dashCd=Math.max(0,p.dashCd-dt);p.abilityCd=Math.max(0,p.abilityCd-dt);p.abilityActive=Math.max(0,p.abilityActive-dt);p.hp=Math.min(p.maxHp,p.hp+p.regen*dt);if(!!k[i?"Numpad0":"KeyE"])useAbility(p);const speed=p.speed*(p.abilityActive>0&&p.ability==="overdrive"?1.45:1);p.x=Math.max(22,Math.min(W-22,p.x+dx*speed*dt));p.y=Math.max(22,Math.min(H-22,p.y+dy*speed*dt));p.fire=Math.max(0,p.fire-dt);let target:Enemy|undefined,best=Infinity;for(const e of s.enemies){const d=(e.x-p.x)**2+(e.y-p.y)**2;if(d<best){best=d;target=e}}if(target&&p.fire<=0){const a=Math.atan2(target.y-p.y,target.x-p.x),shots=p.shots;for(let n=0;n<shots;n++){const spread=(n-(shots-1)/2)*.10;let dmg=15*p.damage;if(Math.random()<p.crit)dmg*=2.5;s.bullets.push({x:p.x,y:p.y,vx:Math.cos(a+spread)*570,vy:Math.sin(a+spread)*570,damage:dmg,life:1.7,enemy:false,r:4,owner:i})}p.fire=Math.max(.055,.25-(s.meta.fire||0)*.02-(p.abilityActive>0&&p.ability==="overdrive"?.10:0))}});
 for(let i=s.bullets.length-1;i>=0;i--){const b=s.bullets[i];b.life-=dt;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.life<=0||b.x<-50||b.x>W+50||b.y<-50||b.y>H+50){s.bullets.splice(i,1);continue}if(b.enemy){let hit=false;for(const p of s.players)if(!p.dead&&p.abilityActive<=0&&Math.hypot(p.x-b.x,p.y-b.y)<20){p.hp-=b.damage*(1-p.armor);hit=true;if(p.hp<=0)p.dead=true;break}if(hit)s.bullets.splice(i,1)}else{for(let ei=s.enemies.length-1;ei>=0;ei--){const e=s.enemies[ei];if(Math.hypot(e.x-b.x,e.y-b.y)<e.r+b.r){e.hp-=b.damage;const p=s.players[b.owner];p.hp=Math.min(p.maxHp,p.hp+b.damage*p.lifesteal);if(e.hp<=0){s.enemies.splice(ei,1);s.kills++;s.credits+=e.kind==="boss"?120:e.elite?10:2+Math.ceil(w*.4);p.score+=e.kind==="boss"?1200:e.elite?60:10;p.xp+=e.kind==="boss"?40:e.elite?12:5;if(p.xp>=p.nextXp){p.xp-=p.nextXp;p.level++;p.nextXp=Math.ceil(p.nextXp*1.27);setScreen("upgrade")}}s.bullets.splice(i,1);break}}}}
 for(const e of s.enemies){const alive=s.players.filter(p=>!p.dead);if(!alive.length)break;let t=alive[0],best=Infinity;for(const p of alive){const d=(p.x-e.x)**2+(p.y-e.y)**2;if(d<best){best=d;t=p}}const a=Math.atan2(t.y-e.y,t.x-e.x),dist=Math.hypot(t.x-e.x,t.y-e.y);if(e.kind==="shooter"&&dist<390){e.x-=Math.cos(a)*e.speed*dt*.45;e.y-=Math.sin(a)*e.speed*dt*.45}else{e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt}if((e.kind==="shooter"||e.kind==="boss")&&Math.random()<dt*(e.kind==="boss"?1.3+w*.025:.5)){s.bullets.push({x:e.x,y:e.y,vx:Math.cos(a)*270,vy:Math.sin(a)*270,damage:e.damage,life:3,enemy:true,r:e.kind==="boss"?8:6,owner:-1})}for(const p of alive)if(Math.hypot(p.x-e.x,p.y-e.y)<e.r+15&&p.abilityActive<=0){p.hp-=e.damage*dt*(e.kind==="boss"?1.15:1)*(1-p.armor);if(p.hp<=0)p.dead=true}}
 if(s.players.every(p=>p.dead)){s.victory=false;setScreen("end");return}if(s.enemies.length===0&&s.time>2){if(w>=MAX_WAVE){s.victory=true;setScreen("end")}else setScreen("upgrade")}redraw()};
 useEffect(()=>{if(screen!=="play")return;const loop=(t:number)=>{const dt=Math.min(.033,(t-last.current||16)/1000);last.current=t;update(dt);raf.current=requestAnimationFrame(loop)};raf.current=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf.current)},[screen]);
 const draw=()=>{const c=canvasRef.current;if(!c)return;const ctx=c.getContext("2d");if(!ctx)return;ctx.fillStyle="#070810";ctx.fillRect(0,0,W,H);ctx.strokeStyle="rgba(255,180,100,.06)";for(let x=0;x<W;x+=60){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=60){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}for(const b of s.bullets){ctx.fillStyle=b.enemy?"#ff4f68":"#ffd18a";ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=12;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,7);ctx.fill()}ctx.shadowBlur=0;for(const e of s.enemies){ctx.fillStyle=e.kind==="boss"?"#ff3d6e":e.kind==="shooter"?"#7fe8ff":e.kind==="charger"?"#ff8fc7":"#ff795c";ctx.beginPath();ctx.arc(e.x,e.y,e.r,0,7);ctx.fill();if(e.elite){ctx.strokeStyle="#ffe66d";ctx.lineWidth=3;ctx.stroke()}ctx.fillStyle="#222";ctx.fillRect(e.x-e.r,e.y-e.r-9,e.r*2,4);ctx.fillStyle="#76ff8b";ctx.fillRect(e.x-e.r,e.y-e.r-9,e.r*2*(e.hp/e.maxHp),4)}for(const p of s.players){if(p.dead)continue;ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=18;ctx.beginPath();ctx.moveTo(p.x+18,p.y);ctx.lineTo(p.x-14,p.y-13);ctx.lineTo(p.x-8,p.y);ctx.lineTo(p.x-14,p.y+13);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#222";ctx.fillRect(p.x-22,p.y+20,44,5);ctx.fillStyle="#65ff9b";ctx.fillRect(p.x-22,p.y+20,44*Math.max(0,p.hp/p.maxHp),5)}ctx.restore?.()};useEffect(()=>{draw()},[screen,s.wave,s.kills,s.credits]);
 const panel={position:"absolute" as const,left:"50%",top:"50%",transform:"translate(-50%,-50%)",background:"rgba(10,8,18,.94)",border:"1px solid rgba(255,180,100,.3)",borderRadius:20,padding:28,color:"white",textAlign:"center" as const,minWidth:320,boxShadow:"0 20px 80px #000"};
 if(screen==="menu")return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"radial-gradient(circle,#29152c,#070810)",color:"white",fontFamily:"system-ui"}}><section style={panel}><h1 style={{fontSize:48,margin:0}}>EMBERFALL</h1><p>Survive. Upgrade. Become ridiculous.</p><button onClick={()=>begin(1)}>SOLO</button> <button onClick={()=>begin(2)}>2 PLAYER</button><p style={{opacity:.65}}>WASD + Space Dash + E Ability</p></section></main>;
 if(screen==="upgrade")return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"#090811",color:"white",fontFamily:"system-ui"}}><section style={panel}><h2>⚡ CHOOSE AN UPGRADE</h2><p>Level up = power up. The arena gets harder every wave.</p><div style={{display:"grid",gap:10}}>{[...UPGRADES].sort(()=>Math.random()-.5).slice(0,4).map(u=><button key={u[2]} onClick={()=>apply(u[2])} style={{padding:14,textAlign:"left",background:"#181323",color:"white",border:"1px solid #59425c",borderRadius:12}}><b>{u[0]}</b><br/><small>{u[1]}</small></button>)}</div></section></main>;
 if(screen==="pause")return <><canvas ref={canvasRef} width={W} height={H} style={{width:"100vw",height:"100vh",display:"block",background:"#070810"}}/><section style={panel}><h2>PAUSED</h2><button onClick={()=>setScreen("play")}>RESUME</button> <button onClick={()=>setScreen("menu")}>MENU</button></section></>;
 if(screen==="end")return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"#090811",color:"white",fontFamily:"system-ui"}}><section style={panel}><h1>{s.victory?"🏆 EMBERFALL CONQUERED":"💀 RUN OVER"}</h1><p>Wave {s.wave} • {s.kills} kills • {s.credits} credits</p><button onClick={()=>begin(1)}>PLAY AGAIN</button> <button onClick={()=>setScreen("menu")}>MENU</button></section></main>;
 return <main style={{position:"relative",minHeight:"100vh",background:"#070810",overflow:"hidden"}}><canvas ref={canvasRef} width={W} height={H} style={{width:"100vw",height:"100vh",display:"block"}}/><div style={{position:"fixed",top:12,left:12,color:"white",fontFamily:"system-ui",fontWeight:700}}>WAVE {s.wave}/{MAX_WAVE} • KILLS {s.kills} • {s.message}<br/>{s.players.map((p,i)=><span key={i} style={{marginRight:18}}>P{i+1} LV{p.level} HP {Math.ceil(p.hp)}/{p.maxHp} • {ABILITIES[p.ability].name} {p.abilityCd>0?Math.ceil(p.abilityCd)+"s":"READY"}</span>)}</div></main>;
}