import { useEffect, useRef, useState } from "react";

type Ability = "nova" | "blink" | "shield" | "overdrive";
type EnemyKind = "husk" | "shooter" | "charger" | "splitter" | "boss";
type Player = {x:number;y:number;hp:number;maxHp:number;speed:number;fire:number;dashCd:number;abilityCd:number;ability:Ability;abilityActive:number;color:string;dead:boolean;level:number;xp:number;nextXp:number;damage:number;shots:number;crit:number;armor:number;regen:number;lifesteal:number;score:number};
type Enemy = {x:number;y:number;r:number;hp:number;maxHp:number;speed:number;damage:number;kind:EnemyKind;elite:boolean;phase:number};
type Bullet = {x:number;y:number;vx:number;vy:number;damage:number;life:number;enemy:boolean;r:number;owner:number};
type Mode = "menu"|"play"|"upgrade"|"pause"|"end"|"settings";
type Settings = {volume:number;shake:boolean;particles:boolean;difficulty:"normal"|"hard";keys:Record<string,string>};
const W=1200,H=675,MAX_WAVE=40,COLORS=["#ff9f43","#65e6ff"];
const DEFAULT_SETTINGS:Settings={volume:70,shake:true,particles:true,difficulty:"normal",keys:{p1up:"KeyW",p1down:"KeyS",p1left:"KeyA",p1right:"KeyD",p1dash:"Space",p1ability:"KeyE",p2up:"ArrowUp",p2down:"ArrowDown",p2left:"ArrowLeft",p2right:"ArrowRight",p2dash:"ShiftRight",p2ability:"Numpad0"}};
const UPGRADES=[
 ["🔥 OVERCHARGE","Damage +18%","damage"],["💨 LIGHT FEET","Speed +10%","speed"],["⚡ QUICK HANDS","Fire cooldown -14%","fire"],["❤️ TITAN CORE","Max HP +30 + heal","hp"],
 ["🛡 ARMOR PLATE","Damage taken -10%","armor"],["🎯 CRITICAL","Crit chance +8%","crit"],["🩸 VAMPIRIC","Heal 3% of damage","lifesteal"],["💚 REGEN","+1.5 HP/sec","regen"],
 ["🔫 TWIN BARREL","+1 projectile","shots"],["☄ HEAVY ROUNDS","Damage +25%","damage"],["🏃 AFTERBURN","Dash cooldown -18%","dash"],["✨ ABILITY CORE","Ability cooldown -20%","ability"],
 ["🧲 MAGNET","XP pickup range +25%","magnet"],["💥 OVERKILL","Crit damage +50%","critDamage"],["🌋 EMBER FUEL","Abilities deal +25%","abilityPower"],["👑 BOSS HUNTER","Boss damage +20%","bossDamage"]
] as const;
const ABILITIES:Record<Ability,{name:string;desc:string;cool:number}>={nova:{name:"NOVA",desc:"Huge blast around you",cool:12},blink:{name:"BLINK",desc:"Teleport forward and dodge damage",cool:9},shield:{name:"EMBER SHIELD",desc:"Become immune for 3 seconds",cool:14},overdrive:{name:"OVERDRIVE",desc:"Move and fire much faster",cool:18}};
function loadSettings():Settings{try{return {...DEFAULT_SETTINGS,...JSON.parse(localStorage.getItem("emberfall.settings.v1")||"{}"),keys:{...DEFAULT_SETTINGS.keys,...(JSON.parse(localStorage.getItem("emberfall.settings.v1")||"{}").keys||{})}}}catch{return DEFAULT_SETTINGS}}
function saveSettings(x:Settings){try{localStorage.setItem("emberfall.settings.v1",JSON.stringify(x))}catch{}}
function loadMeta():Record<string,number>{try{return JSON.parse(localStorage.getItem("emberfall.meta.v5")||"{}")}catch{return {}}}
function saveMeta(x:Record<string,number>){try{localStorage.setItem("emberfall.meta.v5",JSON.stringify(x))}catch{}}
const label=(code:string)=>code.replace("Key","").replace("Arrow","↑ ").replace("Right", " R").replace("Left"," L").replace("Space","SPACE").replace("Numpad0","NUM 0");

export default function Game(){
 const canvasRef=useRef<HTMLCanvasElement>(null),keys=useRef<Record<string,boolean>>({}),last=useRef(0),raf=useRef(0),settingsRef=useRef<Settings>(loadSettings());
 const [,force]=useState(0);const [screen,setScreen]=useState<Mode>("menu");const [settings,setSettings]=useState(settingsRef.current);const [rebinding,setRebinding]=useState<string|null>(null);
 const s=useRef({players:[] as Player[],enemies:[] as Enemy[],bullets:[] as Bullet[],wave:0,time:0,spawn:0,kills:0,credits:0,shake:0,message:"",meta:loadMeta(),victory:false,abilityPower:1,bossDamage:1,critDamage:2.5}).current;
 const redraw=()=>force(v=>v+1);
 const updateSettings=(patch:Partial<Settings>)=>{const n={...settings,...patch};settingsRef.current=n;setSettings(n);saveSettings(n)};
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if(rebinding){const n={...settingsRef.current,keys:{...settingsRef.current.keys,[rebinding]:e.code}};settingsRef.current=n;setSettings(n);saveSettings(n);setRebinding(null);e.preventDefault();return}keys.current[e.code]=true;if(["Space","ArrowUp","ArrowDown","ArrowLeft","ArrowRight"].includes(e.code))e.preventDefault();if(e.code==="Escape")setScreen(x=>x==="play"?"pause":x==="pause"?"play":x)};const up=(e:KeyboardEvent)=>keys.current[e.code]=false;addEventListener("keydown",down);addEventListener("keyup",up);return()=>{removeEventListener("keydown",down);removeEventListener("keyup",up)}},[rebinding]);
 const begin=(count:1|2)=>{const make=(i:number):Player=>({x:W/2+(i?75:-75),y:H-100,hp:100,maxHp:100,speed:215,fire:0,dashCd:0,abilityCd:0,ability:i?"shield":"nova",abilityActive:0,color:COLORS[i],dead:false,level:1,xp:0,nextXp:30,damage:1,shots:1,crit:.05,armor:0,regen:0,lifesteal:0,score:0});s.players=Array.from({length:count},(_,i)=>make(i));s.enemies=[];s.bullets=[];s.wave=0;s.time=0;s.spawn=0;s.kills=0;s.credits=0;s.shake=0;s.victory=false;s.abilityPower=1;s.bossDamage=1;s.critDamage=2.5;nextWave()};
 const nextWave=()=>{s.wave++;s.time=0;s.spawn=0;s.enemies=[];s.bullets=[];if(s.wave>MAX_WAVE){s.victory=true;setScreen("end");return}s.message=s.wave%5===0?"⚠ BOSS WAVE — SOMETHING LARGE HAS ENTERED THE CHAT":"WAVE "+s.wave;setScreen("play");redraw()};
 const apply=(kind:string)=>{for(const p of s.players){if(kind==="damage")p.damage*=1.18;if(kind==="speed")p.speed*=1.10;if(kind==="fire")p.fire=Math.max(0,p.fire-.14);if(kind==="hp"){p.maxHp+=30;p.hp=p.maxHp}if(kind==="armor")p.armor=Math.min(.65,p.armor+.10);if(kind==="crit")p.crit=Math.min(.75,p.crit+.08);if(kind==="lifesteal")p.lifesteal=Math.min(.25,p.lifesteal+.03);if(kind==="regen")p.regen+=1.5;if(kind==="shots")p.shots=Math.min(6,p.shots+1);if(kind==="dash")p.dashCd=Math.max(.25,p.dashCd-.18);if(kind==="ability")p.abilityCd=Math.max(1,p.abilityCd-1.8)}if(kind==="abilityPower")s.abilityPower+=.25;if(kind==="critDamage")s.critDamage+=.5;if(kind==="bossDamage")s.bossDamage+=.2;nextWave()};
 const useAbility=(p:Player)=>{if(p.abilityCd>0||p.dead)return;const a=p.ability;if(a==="nova"){for(let i=s.enemies.length-1;i>=0;i--){const e=s.enemies[i];if(Math.hypot(e.x-p.x,e.y-p.y)<240){e.hp-=220*p.damage*s.abilityPower;if(e.hp<=0){s.enemies.splice(i,1);s.kills++;s.credits+=8}}}s.shake=14;p.abilityCd=ABILITIES[a].cool}else if(a==="blink"){const k=keys.current,dx=Number(!!k.KeyD)-Number(!!k.KeyA),dy=Number(!!k.KeyS)-Number(!!k.KeyW),l=Math.hypot(dx,dy)||1;p.x=Math.max(25,Math.min(W-25,p.x+dx/l*250));p.y=Math.max(25,Math.min(H-25,p.y+dy/l*250));p.abilityActive=.7;p.abilityCd=ABILITIES[a].cool}else if(a==="shield"){p.abilityActive=3;p.abilityCd=ABILITIES[a].cool}else{p.abilityActive=5;p.abilityCd=ABILITIES[a].cool}};
 const spawn=()=>{const w=s.wave,a=Math.random()*Math.PI*2,r=520,boss=w%5===0&&!s.enemies.some(e=>e.kind==="boss"),roll=Math.random();const kind:EnemyKind=boss?"boss":w>=12&&roll<.08?"splitter":roll<.22?"shooter":roll<.38?"charger":"husk";const hard=settingsRef.current.difficulty==="hard"?1.18:1;const scale=(1+(w-1)*.085)*hard;const hp=(kind==="boss"?900+w*230:kind==="splitter"?75+w*8:kind==="charger"?55+w*9:kind==="shooter"?42+w*7:28+w*6)*scale;s.enemies.push({x:W/2+Math.cos(a)*r,y:H/2+Math.sin(a)*r,r:kind==="boss"?46:kind==="charger"?20:kind==="splitter"?19:kind==="shooter"?16:14,hp,maxHp:hp,speed:kind==="boss"?38+w:kind==="charger"?120+w*2:kind==="shooter"?58+w:kind==="splitter"?65+w:76+w*1.6,damage:(kind==="boss"?24+w:7+w*.85)*hard,kind,elite:kind!=="boss"&&w>=6&&Math.random()<Math.min(.30,w*.012),phase:0})};
 const update=(dt:number)=>{s.time+=dt;s.spawn-=dt;s.shake=Math.max(0,s.shake-dt*25);const w=s.wave;const cap=Math.min(95,7+Math.floor(w*2.3));if(s.spawn<=0&&s.enemies.length<cap){spawn();s.spawn=Math.max(.09,.78-w*.015)}
 s.players.forEach((p,i)=>{if(p.dead)return;const k=keys.current,pre=i?"p2":"p1",left=!!k[settingsRef.current.keys[pre+"left"]],right=!!k[settingsRef.current.keys[pre+"right"]],up=!!k[settingsRef.current.keys[pre+"up"]],down=!!k[settingsRef.current.keys[pre+"down"]];let dx=Number(right)-Number(left),dy=Number(down)-Number(up),l=Math.hypot(dx,dy)||1;dx/=l;dy/=l;if(!!k[settingsRef.current.keys[pre+"dash"]]&&p.dashCd<=0&&(dx||dy)){p.dashCd=.9;p.x=Math.max(25,Math.min(W-25,p.x+dx*p.speed*3.6*.18));p.y=Math.max(25,Math.min(H-25,p.y+dy*p.speed*3.6*.18));s.shake=3}p.dashCd=Math.max(0,p.dashCd-dt);p.abilityCd=Math.max(0,p.abilityCd-dt);p.abilityActive=Math.max(0,p.abilityActive-dt);p.hp=Math.min(p.maxHp,p.hp+p.regen*dt);if(k[settingsRef.current.keys[pre+"ability"]])useAbility(p);const boost=p.ability==="overdrive"&&p.abilityActive>0?1.45:1;const speed=p.speed*boost;p.x=Math.max(22,Math.min(W-22,p.x+dx*speed*dt));p.y=Math.max(22,Math.min(H-22,p.y+dy*speed*dt));p.fire=Math.max(0,p.fire-dt);let target:Enemy|undefined,best=Infinity;for(const e of s.enemies){const d=(e.x-p.x)**2+(e.y-p.y)**2;if(d<best){best=d;target=e}}if(target&&p.fire<=0){const a=Math.atan2(target.y-p.y,target.x-p.x);for(let n=0;n<p.shots;n++){const spread=(n-(p.shots-1)/2)*.09;let dmg=15*p.damage;if(Math.random()<p.crit)dmg*=s.critDamage;if(target.kind==="boss")dmg*=s.bossDamage;s.bullets.push({x:p.x,y:p.y,vx:Math.cos(a+spread)*570,vy:Math.sin(a+spread)*570,damage:dmg,life:1.7,enemy:false,r:4,owner:i})}p.fire=Math.max(.045,.25-(s.meta.fire||0)*.02-(p.abilityActive>0&&p.ability==="overdrive"?.11:0))}});
 for(let i=s.bullets.length-1;i>=0;i--){const b=s.bullets[i];b.life-=dt;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.life<=0||b.x<-50||b.x>W+50||b.y<-50||b.y>H+50){s.bullets.splice(i,1);continue}if(b.enemy){let hit=false;for(const p of s.players)if(!p.dead&&p.abilityActive<=0&&Math.hypot(p.x-b.x,p.y-b.y)<20){p.hp-=b.damage*(1-p.armor);hit=true;if(p.hp<=0)p.dead=true;break}if(hit)s.bullets.splice(i,1)}else{for(let ei=s.enemies.length-1;ei>=0;ei--){const e=s.enemies[ei];if(Math.hypot(e.x-b.x,e.y-b.y)<e.r+b.r){e.hp-=b.damage;const p=s.players[b.owner];p.hp=Math.min(p.maxHp,p.hp+b.damage*p.lifesteal);if(e.hp<=0){s.enemies.splice(ei,1);s.kills++;s.credits+=e.kind==="boss"?120:e.elite?10:2+Math.ceil(w*.4);p.score+=e.kind==="boss"?1200:e.elite?60:10;p.xp+=e.kind==="boss"?40:e.elite?12:5;if(e.kind==="boss")s.message="💀 BOSS DELETED. It had a family.";if(e.kind==="splitter"&&w>=14){for(let q=0;q<2;q++)s.enemies.push({x:e.x+(q?12:-12),y:e.y,r:9,hp:20+w*2,maxHp:20+w*2,speed:100+w,damage:5+w*.5,kind:"husk",elite:false,phase:0})}if(p.xp>=p.nextXp){p.xp-=p.nextXp;p.level++;p.nextXp=Math.ceil(p.nextXp*1.27);setScreen("upgrade")}}s.bullets.splice(i,1);break}}}}
 for(const e of s.enemies){const alive=s.players.filter(p=>!p.dead);if(!alive.length)break;let t=alive[0],best=Infinity;for(const p of alive){const d=(p.x-e.x)**2+(p.y-e.y)**2;if(d<best){best=d;t=p}}const a=Math.atan2(t.y-e.y,t.x-e.x),dist=Math.hypot(t.x-e.x,t.y-e.y);if(e.kind==="shooter"&&dist<390){e.x-=Math.cos(a)*e.speed*dt*.45;e.y-=Math.sin(a)*e.speed*dt*.45}else{e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt}if((e.kind==="shooter"||e.kind==="boss")&&Math.random()<dt*(e.kind==="boss"?1.3+w*.025:.5)){s.bullets.push({x:e.x,y:e.y,vx:Math.cos(a)*270,vy:Math.sin(a)*270,damage:e.damage,life:3,enemy:true,r:e.kind==="boss"?8:6,owner:-1})}for(const p of alive)if(Math.hypot(p.x-e.x,p.y-e.y)<e.r+15&&p.abilityActive<=0){p.hp-=e.damage*dt*(e.kind==="boss"?1.15:1)*(1-p.armor);if(p.hp<=0)p.dead=true}}
 if(s.players.every(p=>p.dead)){s.victory=false;setScreen("end");return}if(s.enemies.length===0&&s.time>2){if(w>=MAX_WAVE){s.victory=true;setScreen("end")}else setScreen("upgrade")}redraw()};
 useEffect(()=>{if(screen!=="play")return;last.current=performance.now();const loop=(t:number)=>{const dt=Math.min(.033,(t-last.current)/1000);last.current=t;update(dt);raf.current=requestAnimationFrame(loop)};raf.current=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf.current)},[screen]);
 const draw=()=>{const c=canvasRef.current;if(!c)return;const ctx=c.getContext("2d");if(!ctx)return;ctx.save();if(settingsRef.current.shake&&s.shake>0)ctx.translate((Math.random()-.5)*s.shake,(Math.random()-.5)*s.shake);ctx.fillStyle="#070810";ctx.fillRect(-20,-20,W+40,H+40);ctx.strokeStyle="rgba(255,180,100,.06)";for(let x=0;x<W;x+=60){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=60){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}for(const b of s.bullets){ctx.fillStyle=b.enemy?"#ff4f68":"#ffd18a";ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=12;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,7);ctx.fill()}ctx.shadowBlur=0;for(const e of s.enemies){ctx.fillStyle=e.kind==="boss"?"#ff3d6e":e.kind==="shooter"?"#7fe8ff":e.kind==="charger"?"#ff8fc7":e.kind==="splitter"?"#b6ff65":"#ff795c";ctx.beginPath();ctx.arc(e.x,e.y,e.r,0,7);ctx.fill();if(e.elite){ctx.strokeStyle="#ffe66d";ctx.lineWidth=3;ctx.stroke()}ctx.fillStyle="#222";ctx.fillRect(e.x-e.r,e.y-e.r-9,e.r*2,4);ctx.fillStyle="#76ff8b";ctx.fillRect(e.x-e.r,e.y-e.r-9,e.r*2*Math.max(0,e.hp/e.maxHp),4)}for(const p of s.players){if(p.dead)continue;ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=18;ctx.beginPath();ctx.moveTo(p.x+18,p.y);ctx.lineTo(p.x-14,p.y-13);ctx.lineTo(p.x-8,p.y);ctx.lineTo(p.x-14,p.y+13);ctx.closePath();ctx.fill();if(p.abilityActive>0){ctx.strokeStyle="#fff";ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,28,0,7);ctx.stroke()}ctx.shadowBlur=0;ctx.fillStyle="#222";ctx.fillRect(p.x-22,p.y+20,44,5);ctx.fillStyle="#65ff9b";ctx.fillRect(p.x-22,p.y+20,44*Math.max(0,p.hp/p.maxHp),5)}ctx.restore()};
 useEffect(()=>{draw()},[screen,s.wave,s.kills,s.credits,settings.shake]);
 const button={padding:"12px 18px",borderRadius:12,border:"1px solid #694b68",background:"#191324",color:"white",fontWeight:800,cursor:"pointer"};const panel={position:"absolute" as const,left:"50%",top:"50%",transform:"translate(-50%,-50%)",background:"rgba(10,8,18,.97)",border:"1px solid rgba(255,180,100,.3)",borderRadius:22,padding:28,color:"white",textAlign:"center" as const,minWidth:360,maxWidth:"92vw",boxShadow:"0 20px 100px #000",fontFamily:"system-ui"};
 if(screen==="menu")return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"radial-gradient(circle at 50% 40%,#351a37,#070810)",color:"white"}}><section style={panel}><div style={{fontSize:12,letterSpacing:5,opacity:.65}}>THE ARENA IS HUNGRY</div><h1 style={{fontSize:56,margin:"8px 0",letterSpacing:3}}>EMBERFALL</h1><p style={{opacity:.8}}>Survive. Upgrade. Become ridiculously overpowered.</p><div style={{display:"grid",gap:10,marginTop:20}}><button style={button} onClick={()=>begin(1)}>🔥 SOLO</button><button style={button} onClick={()=>begin(2)}>⚡ LOCAL 2 PLAYER</button><button style={button} onClick={()=>setScreen("settings")}>⚙ SETTINGS</button></div><p style={{fontSize:12,opacity:.5,marginTop:18}}>Normal starts fair. Wave 40 does not.</p></section></main>;
 if(screen==="settings")return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"#090811",color:"white"}}><section style={{...panel,maxHeight:"90vh",overflow:"auto",textAlign:"left"}}><h2 style={{marginTop:0}}>⚙ SETTINGS</h2><p style={{opacity:.65}}>Everything here actually saves.</p><label>🔊 Volume: {settings.volume}% <input type="range" min="0" max="100" value={settings.volume} onChange={e=>updateSettings({volume:+e.target.value})}/></label><div style={{margin:"14px 0"}}><button style={button} onClick={()=>updateSettings({shake:!settings.shake})}>Screen Shake: {settings.shake?"ON":"OFF"}</button> <button style={button} onClick={()=>updateSettings({particles:!settings.particles})}>Particles: {settings.particles?"ON":"OFF"}</button></div><div style={{margin:"14px 0"}}><b>Difficulty</b><br/><button style={button} onClick={()=>updateSettings({difficulty:"normal"})}>🙂 NORMAL</button> <button style={button} onClick={()=>updateSettings({difficulty:"hard"})}>💀 HARD</button></div><h3>🎮 KEYBINDS</h3><p style={{fontSize:12,opacity:.6}}>Click a key, then press the new key. No keyboard wizardry required.</p>{Object.entries(settings.keys).map(([k,v])=><div key={k} style={{display:"flex",justifyContent:"space-between",gap:12,margin:"7px 0",padding:9,background:"#14101d",borderRadius:9}}><span>{k.replace("p1","P1 ").replace("p2","P2 ")}</span><button style={{...button,padding:"7px 11px"}} onClick={()=>setRebinding(k)}>{rebinding===k?"PRESS KEY…":label(v)}</button></div>)}<div style={{marginTop:18}}><button style={button} onClick={()=>{settingsRef.current=DEFAULT_SETTINGS;setSettings(DEFAULT_SETTINGS);saveSettings(DEFAULT_SETTINGS)}}>RESET SETTINGS</button> <button style={button} onClick={()=>setScreen("menu")}>BACK</button></div></section></main>;
 if(screen==="upgrade")return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"radial-gradient(circle,#211528,#090811)",color:"white"}}><section style={panel}><h2>⚡ LEVEL UP!</h2><p>Pick one. Then the arena gets nastier.</p><div style={{display:"grid",gap:10}}>{[...UPGRADES].sort(()=>Math.random()-.5).slice(0,4).map(u=><button key={u[2]} onClick={()=>apply(u[2])} style={{...button,textAlign:"left",padding:15}}><b>{u[0]}</b><br/><small style={{opacity:.7}}>{u[1]}</small></button>)}</div></section></main>;
 if(screen==="pause")return <><canvas ref={canvasRef} width={W} height={H} style={{width:"100vw",height:"100vh",display:"block"}}/><section style={panel}><h2>⏸ PAUSED</h2><button style={button} onClick={()=>setScreen("play")}>RESUME</button> <button style={button} onClick={()=>setScreen("settings")}>⚙ SETTINGS</button> <button style={button} onClick={()=>setScreen("menu")}>MENU</button></section></>;
 if(screen==="end")return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"#090811",color:"white"}}><section style={panel}><h1>{s.victory?"🏆 EMBERFALL CONQUERED":"💀 RUN OVER"}</h1><p>Wave {s.wave} • {s.kills} kills • {s.credits} credits</p><p style={{opacity:.7}}>{s.victory?"You bullied the entire ecosystem.":"The ecosystem has filed a complaint."}</p><button style={button} onClick={()=>begin(1)}>PLAY AGAIN</button> <button style={button} onClick={()=>setScreen("menu")}>MENU</button></section></main>;
 return <main style={{position:"relative",minHeight:"100vh",background:"#070810",overflow:"hidden"}}><canvas ref={canvasRef} width={W} height={H} style={{width:"100vw",height:"100vh",display:"block"}}/><div style={{position:"fixed",top:12,left:12,right:12,color:"white",fontWeight:800,fontFamily:"system-ui",textShadow:"0 2px 8px #000",pointerEvents:"none"}}>WAVE {s.wave}/{MAX_WAVE} • KILLS {s.kills} • {s.message}<br/>{s.players.map((p,i)=><span key={i} style={{marginRight:18}}>P{i+1} LV{p.level} HP {Math.ceil(p.hp)}/{p.maxHp} • {ABILITIES[p.ability].name} {p.abilityCd>0?Math.ceil(p.abilityCd)+"s":"READY"}</span>)}<span style={{float:"right",pointerEvents:"auto"}}><button style={{...button,padding:"7px 10px"}} onClick={()=>setScreen("pause")}>Ⅱ</button></span></div></main>;
}