import {useEffect,useRef,useState} from "react";

type Player={x:number;y:number;hp:number;max:number;speed:number;fire:number;dash:number;cool:number;color:string;dead:boolean;score:number;level:number;xp:number;next:number;damage:number;shots:number};
type Enemy={x:number;y:number;r:number;hp:number;max:number;speed:number;damage:number;kind:string;color:string;elite:boolean;boss:boolean};
type Bullet={x:number;y:number;vx:number;vy:number;damage:number;life:number;owner:number;enemy?:boolean;r:number};
const W=1200,H=675,MAX_WAVE=30;
const colors=["#ff9f43","#65e6ff"];
const names=["ASH","VALE"];
const upgrades=[
 ["HOT CORES","+20% weapon damage","damage"],["LIGHT BOOTS","+15% movement speed","speed"],["QUICK HANDS","-15% fire cooldown","fire"],["REINFORCED","+25 max HP and heal","hp"],["DASH COILS","-20% dash cooldown","dash"],["SCAVENGER","+30% XP and credits","loot"]
] as const;

function loadMeta(){try{return JSON.parse(localStorage.getItem("emberfall.meta.v2")||"{}")}catch{return {}}}
function saveMeta(m:Record<string,number>){try{localStorage.setItem("emberfall.meta.v2",JSON.stringify(m))}catch{}}

export default function Game(){
 const canvas=useRef<HTMLCanvasElement>(null); const keys=useRef<Record<string,boolean>>({}); const raf=useRef(0); const last=useRef(0);
 const state=useRef<{players:Player[];enemies:Enemy[];bullets:Bullet[];wave:number;timer:number;spawn:number;kills:number;credits:number;shake:number;message:string;mode:"menu"|"play"|"upgrade"|"end";victory:boolean;meta:Record<string,number>;boss:boolean}>({players:[],enemies:[],bullets:[],wave:0,timer:0,spawn:0,kills:0,credits:0,shake:0,message:"",mode:"menu",victory:false,meta:loadMeta(),boss:false});
 const [,redraw]=useState(0); const s=state.current;
 const [screen,setScreen]=useState("menu");
 const sync=()=>redraw(v=>v+1);
 useEffect(()=>{const d=(e:KeyboardEvent)=>{keys.current[e.code]=true;if(["Space","ArrowUp","ArrowDown","ArrowLeft","ArrowRight"].includes(e.code))e.preventDefault();if(e.code==="Escape"&&s.mode==="play"){s.mode="menu";setScreen("menu");sync()}};const u=(e:KeyboardEvent)=>keys.current[e.code]=false;window.addEventListener("keydown",d);window.addEventListener("keyup",u);return()=>{window.removeEventListener("keydown",d);window.removeEventListener("keyup",u);cancelAnimationFrame(raf.current)}},[]);
 const start=(players=1)=>{const meta=s.meta;const make=(i:number):Player=>({x:W/2+(i?70:-70),y:H-100,hp:100,max:100,speed:210,fire:0,dash:0,cool:0,color:colors[i],dead:false,score:0,level:1,xp:0,next:35,damage:1,shots:1});s.players=Array.from({length:players},(_,i)=>make(i));s.enemies=[];s.bullets=[];s.wave=0;s.timer=0;s.spawn=0;s.kills=0;s.credits=0;s.shake=0;s.message="GET READY";s.mode="play";s.victory=false;s.boss=false;for(const p of s.players){p.damage*=1+(.08*(meta.damage||0));p.speed*=1+(.05*(meta.speed||0));p.max+=20*(meta.hp||0);p.hp=p.max}setScreen("play");nextWave();};
 const nextWave=()=>{s.wave++;s.timer=0;s.spawn=0;s.boss=s.wave%5===0;s.message=s.boss?"BOSS INCOMING":"WAVE "+s.wave;s.enemies=[];s.bullets=[];if(s.wave>MAX_WAVE){s.mode="end";s.victory=true;setScreen("end");}else{setScreen("play");sync()}};
 const choose=(kind:string)=>{for(const p of s.players){if(kind==="damage")p.damage*=1.2;if(kind==="speed")p.speed*=1.15;if(kind==="fire")p.fire=Math.max(0.035,p.fire*0.85);if(kind==="hp"){p.max+=25;p.hp=p.max}if(kind==="dash")p.dash=Math.max(0,p.dash-.2)}s.mode="play";nextWave();};
 useEffect(()=>{const loop=(t:number)=>{raf.current=requestAnimationFrame(loop);const dt=Math.min(.033,(t-last.current||16)/1000);last.current=t;if(s.mode!=="play")return;update(dt);draw();};raf.current=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf.current)},[]);
 const update=(dt:number)=>{
  s.timer+=dt;s.spawn-=dt;s.shake=Math.max(0,s.shake-dt*30);
  const wave=s.wave,diff=1+Math.max(0,wave-1)*.075;
  if(s.spawn<=0&&s.enemies.length<Math.min(80,10+wave*2)){s.spawn=Math.max(.12,.7-wave*.015);const a=Math.random()*Math.PI*2,dist=500;const boss=s.boss&&s.enemies.length===0&&Math.random()<.12;const hp=(boss?700+wave*180:24+wave*10)*diff;const kind=boss?"BOSS":Math.random()<.18?"SHOOTER":Math.random()<.15?"CHARGER":"HUSK";s.enemies.push({x:W/2+Math.cos(a)*dist,y:H/2+Math.sin(a)*dist,r:boss?42:kind==="CHARGER"?20:kind==="SHOOTER"?16:14,hp,max:hp,speed:(boss?42:kind==="CHARGER"?115:kind==="SHOOTER"?60:75)+wave*1.4,damage:(boss?24:8+wave*.8),kind,color:boss?"#ff3d6e":kind==="SHOOTER"?"#7fe8ff":kind==="CHARGER"?"#ff8fc7":"#ff7a5c",elite:!boss&&Math.random()<Math.min(.22,wave*.012),boss});}
  s.players.forEach((p,i)=>{if(p.dead)return;const k=keys.current;const left=k[i?"ArrowLeft":"KeyA"],right=k[i?"ArrowRight":"KeyD"],up=k[i?"ArrowUp":"KeyW"],down=k[i?"ArrowDown":"KeyS"];let x=(right?1:0)-(left?1:0),y=(down?1:0)-(up?1:0);const len=Math.hypot(x,y)||1;x/=len;y/=len;if(k[i?"ShiftRight":"Space"]&&!p.cool&&len>0){p.cool=.9;p.dash=.16}s.players[i].cool=Math.max(0,p.cool-dt);const sp=p.speed*(p.dash>0?3.5:1);p.dash=Math.max(0,p.dash-dt);p.x=Math.max(18,Math.min(W-18,p.x+x*sp*dt));p.y=Math.max(18,Math.min(H-18,p.y+y*sp*dt));p.fire=Math.max(0,p.fire-dt);let target:Enemy|undefined;let bd=1e9;for(const e of s.enemies){const d=(e.x-p.x)**2+(e.y-p.y)**2;if(d<bd){bd=d;target=e}}if(target&&p.fire<=0){const a=Math.atan2(target.y-p.y,target.x-p.x);for(let n=0;n<p.shots;n++){const spread=(n-(p.shots-1)/2)*.12;s.bullets.push({x:p.x,y:p.y,vx:Math.cos(a+spread)*560,vy:Math.sin(a+spread)*560,damage:14*p.damage,life:1.7,owner:i,r:4})}p.fire=.22*(.85**(s.meta.fire||0))}});
  for(let i=s.bullets.length-1;i>=0;i--){const b=s.bullets[i];b.life-=dt;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.life<=0){s.bullets.splice(i,1);continue}if(b.enemy){for(const p of s.players)if(!p.dead&&Math.hypot(p.x-b.x,p.y-b.y)<18){p.hp-=b.damage;s.shake=7;s.bullets.splice(i,1);if(p.hp<=0)p.dead=true;break}}else{let hit=false;for(const e of s.enemies){if(Math.hypot(e.x-b.x,e.y-b.y)<e.r+b.r){e.hp-=b.damage;hit=true;if(e.hp<=0){const idx=s.enemies.indexOf(e);if(idx>=0)s.enemies.splice(idx,1);s.kills++;s.credits+=e.boss?100:Math.ceil(2+wave*.4);const p=s.players[b.owner];p.xp+=e.boss?30:6;if(p.xp>=p.next){p.xp-=p.next;p.level++;p.next=Math.round(p.next*1.28);s.mode="upgrade";setScreen("upgrade");}s.message=e.boss?"BOSS DOWN!":Math.random()<.035?["BONK.","ASHES TO ASHES","THAT LOOKED EXPENSIVE","GET REKT"][Math.floor(Math.random()*4)]:s.message}}break}}if(hit)s.bullets.splice(i,1)}}
  for(const e of s.enemies){let target=s.players.find(p=>!p.dead);if(!target)break;let bd=1e9;for(const p of s.players)if(!p.dead){const d=(p.x-e.x)**2+(p.y-e.y)**2;if(d<bd){bd=d;target=p}}const a=Math.atan2(target.y-e.y,target.x-e.x);e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt;if(e.kind==="SHOOTER"&&Math.random()<dt*.5)s.bullets.push({x:e.x,y:e.y,vx:Math.cos(a)*260,vy:Math.sin(a)*260,damage:e.damage,life:3,owner:-1,enemy:true,r:6});for(const p of s.players)if(!p.dead&&Math.hypot(p.x-e.x,p.y-e.y)<e.r+15){p.hp-=e.damage*dt*(e.boss?1.2:1);if(p.hp<=0)p.dead=true}}
  if(s.players.every(p=>p.dead)){s.mode="end";s.victory=false;setScreen("end");sync();return}if(s.enemies.length===0&&s.timer>2){if(s.wave>=MAX_WAVE){s.mode="end";s.victory=true;setScreen("end")}else{s.mode="upgrade";setScreen("upgrade")}}sync();
 };
 const draw=()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext("2d");if(!ctx)return;ctx.save();const sx=(Math.random()-.5)*s.shake,sy=(Math.random()-.5)*s.shake;ctx.translate(sx,sy);const g=ctx.createRadialGradient(W/2,H/2,30,W/2,H/2,800);g.addColorStop(0,"#24172b");g.addColorStop(1,"#080912");ctx.fillStyle=g;ctx.fillRect(-20,-20,W+40,H+40);ctx.strokeStyle="rgba(255,180,100,.07)";for(let x=0;x<W;x+=60){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=60){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}for(const b of s.bullets){ctx.fillStyle=b.enemy?"#ff526e":"#ffd18a";ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=12;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill()}for(const e of s.enemies){ctx.save();ctx.translate(e.x,e.y);ctx.fillStyle=e.color;ctx.shadowColor=e.color;ctx.shadowBlur=e.boss?28:e.elite?16:8;if(e.boss){ctx.rotate(s.timer);ctx.beginPath();for(let i=0;i<8;i++){const a=i*Math.PI/4,r=i%2?e.r*.65:e.r;ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.fill()}else{ctx.beginPath();ctx.arc(0,0,e.r,0,Math.PI*2);ctx.fill()}ctx.restore();ctx.fillStyle="rgba(0,0,0,.55)";ctx.fillRect(e.x-e.r,e.y-e.r-9,e.r*2,3);ctx.fillStyle=e.color;ctx.fillRect(e.x-e.r,e.y-e.r-9,e.r*2*Math.max(0,e.hp/e.max),3)}for(const p of s.players)if(!p.dead){ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=20;ctx.rotate(Math.atan2((s.enemies[0]?.y??p.y)-p.y,(s.enemies[0]?.x??p.x)-p.x));ctx.beginPath();ctx.moveTo(20,0);ctx.lineTo(-14,12);ctx.lineTo(-9,0);ctx.lineTo(-14,-12);ctx.closePath();ctx.fill();ctx.restore()}ctx.restore()};
 if(screen==="menu")return <main className="game-shell flex min-h-screen items-center justify-center p-6"><section className="glass w-full max-w-3xl rounded-3xl p-8 sm:p-12"><div className="text-center"><p className="mb-3 text-xs font-bold tracking-[.45em] text-primary">A CO-OP SURVIVAL GAME</p><h1 className="text-6xl font-black tracking-[.16em] text-primary sm:text-8xl">EMBERFALL</h1><p className="mx-auto mt-5 max-w-xl text-base leading-7 text-muted-foreground">Start simple. Build power. Survive the chaos. Every five waves, something meaner arrives.</p></div><div className="mx-auto mt-9 grid max-w-xl gap-3"><button className="menu-button rounded-2xl px-6 py-4 text-lg font-black" onClick={()=>start(1)}>PLAY SOLO <span className="ml-2 text-muted-foreground">WASD + SPACE</span></button><button className="menu-button rounded-2xl px-6 py-4 text-lg font-black" onClick={()=>start(2)}>PLAY CO-OP <span className="ml-2 text-muted-foreground">P2 ARROWS + SHIFT</span></button></div><div className="mt-8 grid grid-cols-3 gap-3 text-center text-xs text-muted-foreground"><div className="glass rounded-xl p-3"><b className="block text-foreground">30</b>WAVES</div><div className="glass rounded-xl p-3"><b className="block text-foreground">6</b>BOSSES</div><div className="glass rounded-xl p-3"><b className="block text-foreground">∞</b>BUILDS</div></div></section></main>;
 if(screen==="upgrade")return <main className="game-shell flex min-h-screen items-center justify-center p-6"><section className="glass w-full max-w-4xl rounded-3xl p-8"><p className="text-center text-xs font-bold tracking-[.35em] text-accent">POWER SPIKE</p><h2 className="mt-2 text-center text-4xl font-black">CHOOSE YOUR UPGRADE</h2><p className="mt-2 text-center text-muted-foreground">Wave {s.wave} cleared. The next wave will be worse. Probably.</p><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{upgrades.map(u=><button key={u[2]} onClick={()=>choose(u[2])} className="menu-button rounded-2xl p-5 text-left"><span className="text-xs font-bold tracking-widest text-primary">UPGRADE</span><h3 className="mt-2 text-xl font-black">{u[0]}</h3><p className="mt-1 text-sm text-muted-foreground">{u[1]}</p></button>)}</div></section></main>;
 if(screen==="end")return <main className="game-shell flex min-h-screen items-center justify-center p-6"><section className="glass w-full max-w-xl rounded-3xl p-10 text-center"><p className="text-xs font-bold tracking-[.4em] text-primary">{s.victory?"CAMPAIGN COMPLETE":"RUN OVER"}</p><h2 className="mt-3 text-5xl font-black">{s.victory?"YOU SURVIVED":"THE ASHES WIN"}</h2><p className="mt-5 text-muted-foreground">Wave {Math.min(s.wave,MAX_WAVE)} · {s.kills} kills · {s.credits} credits</p><p className="mt-3 text-lg font-bold text-accent">{s.victory?"Okay, that was actually impressive.":"The next run will be better. Probably."}</p><button className="menu-button mt-8 rounded-2xl px-8 py-4 font-black" onClick={()=>{s.mode="menu";setScreen("menu")}}>PLAY AGAIN</button></section></main>;
 return <main className="game-shell flex min-h-screen flex-col items-center justify-center gap-3 p-3"><div className="flex w-full max-w-[1200px] items-center justify-between rounded-2xl px-4 py-2 glass"><div><b className="tracking-widest text-primary">EMBERFALL</b><span className="ml-4 text-sm text-muted-foreground">WAVE {s.wave}/{MAX_WAVE}</span></div><div className="text-sm"><span className="mr-4 text-muted-foreground">KILLS {s.kills}</span><span className="font-bold text-accent">{s.credits}¢</span></div></div><div className="relative w-full max-w-[1200px] overflow-hidden rounded-2xl border border-white/10 shadow-2xl" style={{aspectRatio:`${W}/${H}`}}><canvas ref={canvas} width={W} height={H} className="h-full w-full"/><div className="pointer-events-none absolute left-1/2 top-6 -translate-x-1/2 text-center"><div className="text-sm font-black tracking-[.35em] text-white/80">{s.message}</div></div></div><div className="grid w-full max-w-[1200px] gap-3 sm:grid-cols-2">{s.players.map((p,i)=><div key={i} className="glass rounded-2xl p-3"><div className="flex justify-between text-sm font-bold"><span style={{color:p.color}}>{names[i]}</span><span>LV {p.level}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full" style={{width:`${Math.max(0,p.hp/p.max)*100}%`,background:p.color}}/></div><div className="mt-2 flex justify-between text-[11px] text-muted-foreground"><span>{Math.ceil(p.hp)}/{p.max} HP</span><span>{p.xp}/{p.next} XP</span><span>x{p.damage.toFixed(1)} DMG</span></div></div>)}</div><p className="text-center text-[11px] text-muted-foreground">P1 WASD + SPACE · P2 ARROWS + RIGHT SHIFT · AUTO-AIM · ESC MENU</p></main>;
}
